# MovieLens 20M Dataset

In [1]:
# https://www.kaggle.com/datasets/grouplens/movielens-20m-dataset === ( dataset download link) 

# https://www.kaggle.com/code/harunshimanto/pandas-with-data-science-ai === (code link) == work till 44th line

In [2]:
import pandas as pd

In [3]:
movies=pd.read_csv(r'D:\MEGH@\AI_Engineer\Practice\Expertise-fullstack-GenAI-Agentic-AI\Kaggle\File\movie.csv')

In [4]:
print(type(movies))
movies.head(20)

<class 'pandas.DataFrame'>

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller
10,11,"American President, The (1995)",Comedy|Drama|Romance
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror
12,13,Balto (1995),Adventure|Animation|Children
13,14,Nixon (1995),Drama
14,15,Cutthroat Island (1995),Action|Adventure|Romance
15,16,Casino (1995),Crime|Drama
16,17,Sense and Sensibility (1995),Drama|Romance
17,18,Four Rooms (1995),Comedy
18,19,Ace Ventura: When Nature Calls (1995),Comedy
19,20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller

In [5]:
tags=pd.read_csv(r'D:\MEGH@\AI_Engineer\Practice\Expertise-fullstack-GenAI-Agentic-AI\Kaggle\File\tag.csv')

In [6]:
tags.head()

   userId  movieId            tag            timestamp
0      18     4141    Mark Waters  2009-04-24 18:19:40
1      65      208      dark hero  2013-05-10 01:41:18
2      65      353      dark hero  2013-05-10 01:41:19
3      65      521  noir thriller  2013-05-10 01:39:43
4      65      592      dark hero  2013-05-10 01:41:18

In [7]:
ratings=pd.read_csv(r'D:\MEGH@\AI_Engineer\Practice\Expertise-fullstack-GenAI-Agentic-AI\Kaggle\File\rating.csv')
ratings.head()

   userId  movieId  rating            timestamp
0       1        2     3.5  2005-04-02 23:53:47
1       1       29     3.5  2005-04-02 23:31:16
2       1       32     3.5  2005-04-02 23:33:39
3       1       47     3.5  2005-04-02 23:32:07
4       1       50     3.5  2005-04-02 23:29:40

In [8]:
del ratings['timestamp']
del tags['timestamp']

In [10]:
row_0=tags.iloc[0]
type(row_0)

pandas.Series

In [11]:
print(row_0)

userId              18
movieId           4141
tag        Mark Waters
Name: 0, dtype: object

In [12]:
row_0.index

Index(['userId', 'movieId', 'tag'], dtype='str')

In [13]:
row_0['userId']

np.int64(18)